name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
    paths:
      - '**.py'
      - 'run_tests.sh'
      - 'tox.ini'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv tox-gh-actions
        uv tool install tox --with tox-uv

    - name: Make setup script executable
      run: chmod +x ./run_tests.sh
        
    - name: Run setup script
      env:
        PATH: "root/.local/bin:${{ env.PATH }}"    
      run: ./run_tests.sh
      
    - name: Run tox
      run: tox