name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]
    paths:
      - '**.py'
      - 'run_tests.sh'
      - 'tox.ini'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv tox

    - name: Install tox-uv
      run: |
        uv tool install tox --with tox-uv

    - name: Make test script executable
      run: chmod +x ./run_tests.sh
        
    - name: Run test script
      env:
        PATH: "root/.local/bin:/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      run: ./run_tests.sh
