name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]
    paths:
      - '**.py'
      - 'run_tests.sh'
      - 'tox.ini'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv ruff
    - name: Run Ruff
      run: ruff check .        
    - name: Install tox
      run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv
    - name: Install Python
      if: startsWith(matrix.env, '3.') && matrix.env != '3.13'
      run: uv python install --python-preference only-managed ${{ matrix.env }}
    - name: Make test script executable
      run: chmod +x ./run_tests.sh
    - name: Run test script
#      env:
#        PATH: "root/.local/bin:/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      run: ./run_tests.sh
    - name: Run test suite vault 1.16.3
      run: tox run --skip-pkg-install -e py${{ matrix.env }}-vault1163
    - name: Run test suite vault 1.17.6
      run: tox run --skip-pkg-install -e py${{ matrix.env }}-vault1176
    - name: Run test suite vault 1.18.3
      run: tox run --skip-pkg-install -e py${{ matrix.env }}-vault1183